<?php

return [
    /**
     * Control if the seeder should create a user per role while seeding the data.
     */
    'create_users' => false,

    /**
     * Control if all the laratrust tables should be truncated before running the seeder.
     */
    'truncate_tables' => true,

    'roles_structure' => [
        'administrator' => [
            'partner' => 'b,r,e,a,d',
            'partner-paygate-config' => 'b,e,a,d',
            'partner-transaction' => 'b,r,x',
            'partner-application' => 'b,r,e,a,d',
            'partner-application-service-config' => 'b,e,a,d',
            'partner-balance' => 'b,r',
            'gate-money-dashboard' => 'b',
            'gate-bank' => 'b,e,a,d',
            'gate-transaction' => 'b,r,x,f',
            'gate-transaction-refund' => 'b,r,x',
            'gate-vendor' => 'b,e,a,d',
            'gate-partner-bank-vendor' => 'b,e,a,d',
            'gate-partner-vendor' => 'b,e,a,d',
            'gate-ipn-log' => 'b,r',
            'gate-money-audit' => 'b,r',
            'charging-card-transaction-dashboard' => 'b',
            'charging-card-transaction' => 'b,r',
            'topup-dashboard' => 'b',
            'topup-denomination' => 'b,e,a,d',
            'topup-transaction' => 'b,r,x,f',
            'topup-provider-config' => 'b,r,e,a,d',
            'topup-telco-provider' => 'b,e,a,d',
            'topup-discount-config' => 'b,e,a,d',
            'bill-service-category' => 'b,e,a,d',
            'bill-service' => 'b,e,a,d',
            'bill-transaction' => 'b,r',
            'bill-provider' => 'b,e,a,d',
            'bill-provider-service-match' => 'b,e,a,d',
            'shopcard-card' => 'b,e,a,d,x',
            'shopcard-card-item' => 'b,r,a,x',
            'shopcard-card-transaction' => 'b,r,x',
            'shopcard-card-partner-card-data' => 'b,r,x',
            'shopcard-card-discount-config' => 'b,e,a,d',
            'ebill-virtual-account-collect-money' => 'b,e,a,d',
            'ebill-virtual-account-ebill' => 'b,r',
            'ebill-virtual-account-ebill-transaction' => 'b,r',
            'ebill-virtual-account-virtual-account' => 'b,r',
            'transfer-money-transaction' => 'b,r,x',
            'transfer-money-provider' => 'b,r,e,a,d',
            'user' => 'b,e',
            'role' => 'b,e,a,d',
            'permission' => 'b,e,a,d',
        ],
        'moderator' => [
            'partner' => 'b,r,e,a,d',
            'partner-paygate-config' => 'b,e,a,d',
            'partner-transaction' => 'b,r',
            'partner-application' => 'b,r,e,a,d',
            'partner-application-service-config' => 'b,e,a,d',
            'partner-balance' => 'b,r',
            'gate-money-dashboard' => 'b',
            'gate-bank' => 'b,e,a,d',
            'gate-transaction' => 'b,r',
            'gate-transaction-refund' => 'b,r',
            'gate-vendor' => 'b,e,a,d',
            'gate-partner-bank-vendor' => 'b,e,a,d',
            'gate-partner-vendor' => 'b,e,a,d',
            'gate-ipn-log' => 'b,r',
            'gate-money-audit' => 'b,r,x',
            'charging-card-transaction-dashboard' => 'b',
            'charging-card-transaction' => 'b,r,x',
            'topup-dashboard' => 'b',
            'topup-transaction' => 'b,r',
            'topup-provider-config' => 'b,r,e,a,d',
            'topup-telco-provider' => 'b,e,a,d',
            'topup-discount-config' => 'b,e,a,d',
            'bill-service-category' => 'b,e,a,d',
            'bill-transaction' => 'b,r',
            'bill-provider' => 'b,e,a,d',
            'bill-provider-service-match' => 'b,e,a,d',
            'shopcard-card' => 'b,e,a,d',
            'shopcard-card-item' => 'b,r,a',
            'shopcard-card-item' => 'b,r,a',
            'shopcard-card-partner-card-data' => 'b,r',
            'shopcard-card-discount-config' => 'b,e,a,d',
            'ebill-virtual-account-collect-money' => 'b,e,a,d',
            'ebill-virtual-account-ebill' => 'b,r',
            'ebill-virtual-account-ebill-transaction' => 'b,r',
            'ebill-virtual-account-virtual-account' => 'b,r',
            'transfer-money-transaction' => 'b,r',
            'transfer-money-provider' => 'b,r,e,a,d',
        ],
    ],

    'permissions_map' => [
        'b' => 'browse',
        'r' => 'read',
        'e' => 'edit',
        'a' => 'add',
        'd' => 'delete',
        'x' => 'export',
        'f' => 'refund',
    ]
];
